# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      #EC2にSSH接続し、デプロイをする。
      - run:
          add_ssh_keys:
          - run: ssh ${USER_NAME}@${HOST_NAME} 'cd privateLibrary && git pull && docker-compose -f docker'