# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  deploy:
      working_directory: ~/home/ec2-user/privateLibrary
      image: circleci/classic:edge
    branches:
      only:
        - making_circleCI
    steps:
      - checkout
      #EC2にSSH接続し、デプロイをする。
      - add_ssh_keys:
        fingerprints:
          - "67:81:ed:9a:2c:ec:f9:94:c7:32:1e:09:f5:f6:65:f7"
      - run:
          command: ssh ${USER_NAME}@${HOST_NAME} 'cd privateLibrary && git pull && docker-compose -f docker-compose.yml restart && docker-exec -it privatelibrary_app_1 sh && php artisan migrate:refresh'